### ISSUE TITLE
Deserialising to generic type using TypeNameHandling.Objects fails

### ISSUE THREAD

**Issue by ProductiveRage** [bridgedotnet/Bridge.Newtonsoft.Json#8]
The following works in .NET but fails with Bridge:

https://deck.net/1dc23903508dfb06404238d527b845fa

```csharp
static class Program
{
    private static void Main()
    {
        var settings = new JsonSerializerSettings
        {
            TypeNameHandling = TypeNameHandling.Objects
        };
        
        var x = new ApiResponse<PageEditData>();
        var json = JsonConvert.SerializeObject(x, settings);
        
        Console.WriteLine(json);

        var result = JsonConvert.DeserializeObject<ApiResponse<PageEditData>>(
            json,
            settings
        );
    }
}

public sealed class ApiResponse<T> { }
public sealed class PageEditData { }
```

### Actual Result

```
System.Exception: TypeError: Cannot find type: Demo.ApiResponse`1[[Demo.PageEditData, Demo]], Demo
    at Function.DeserializeObject (https://deck.net/resources/js/bridge/newtonsoft.json.js?16.0.0-beta3:620:39)
    at Function.Main (https://deck.net/RunHandler.ashx?h=-1340629354:23:54)
    at https://deck.net/resources/js/bridge/bridge.js?16.0.0-beta3:3180:39
    at HTMLDocument.delayfn (https://deck.net/resources/js/bridge/bridge.js?16.0.0-beta3:469:21)
    at i (https://code.jquery.com/jquery-2.2.4.min.js:2:27151)
    at Object.add [as done] (https://code.jquery.com/jquery-2.2.4.min.js:2:27450)
    at n.fn.init.n.fn.ready (https://code.jquery.com/jquery-2.2.4.min.js:2:29515)
    at n.fn.init (https://code.jquery.com/jquery-2.2.4.min.js:2:24945)
    at n (https://code.jquery.com/jquery-2.2.4.min.js:2:405)
    at Object.ready (https://deck.net/resources/js/bridge/bridge.js?16.0.0-beta3:474:31)
```

Looking in the DeserializeObject method, I see this:

```js
type = Bridge.Reflection.getType(raw["$type"].split(",")[0]);
```

This looks a bit suspect.. If I had multiple generic type parameters then it wouldn't just be the assembly name which would be trimmed off the type name string, it would be every type parameter other than the first one. Or is the problem that `getType` doesn't work with "populated" generic types and it needs the type without _any_ type parameter values and then needs to recursively loop through the type parameter names to populate them to get the final type?

I imagine that if my fairly-simple case is failing then more deeply-nested generic types (eg. `ApiResponse<MyData<Page>>`)  or those with multiple type parameters (eg.`ApiResponse<Page, User>`) or both (`ApiResponse<MyData<Page, PageID>, User>`) will be causing trouble as well.

**Comment by geoffreymcgill** [comment]
Thanks for the pointing out this defect and for the excellent sample demonstrating how to reproduce. We will investigate and try to fix right away.

**Comment by DanTup** [comment]
@LeonidVeriga Is this the same issue as https://github.com/bridgedotnet/Bridge/issues/2679? Looks like that was fixed, though the issue looks the same.

**Comment by DanTup** [comment]
(looks like the bottom half of the issue was edited in later, so maybe it wasn't there when you made the code changes?)

**Comment by LeonidVeriga** [comment]
@DanTup, no, this issue is still to be fixed.

As rightly noted by @ProductiveRage, statement `type = Bridge.Reflection.getType(raw["$type"].split(",")[0]);` should be corrected.

**Comment by DanTup** [comment]
@LeonidVeriga What's the status of this? It's closed and there's a PR, but we're still seeing it in v1.0.0 which seems more recent than the date on the PR.

We're getting strings that look like this as our types (from JSON.NET):

`"NewMind.Hercules.Common.APIs.ApiResponse`1[[CreateMailoutTask.KeyValuePairDataModel[], NewMind.Hercules.CreateMailoutTask]]"`

The deserialisation code seems to split on the comma and then assume `NewMind.Hercules.CreateMailoutTask]]` is the assembly name (note the trailing closing brackets).

**Comment by geoffreymcgill** [comment]
Hi @DanTup,

I've reopened the issue and we will investigate to determine what is going wrong. 

When I run the original [sample](https://dotnetfiddle.net/hNwczs) on DotNetFiddle an exception is thrown. Maybe this exception is just related to DotNetFiddle and not actually a problem.

```
{"$type":"ApiResponse`1[[PageEditData, ityhev2u]], ityhev2u"}
Run-time exception (line 18): Error resolving type specified in JSON 'ApiResponse`1[[PageEditData, ityhev2u]], ityhev2u'. Path '$type', line 1, position 60.

Stack Trace:

[Newtonsoft.Json.JsonSerializationException: Could not load assembly 'ityhev2u'.]

[Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'ApiResponse`1[[PageEditData, ityhev2u]], ityhev2u'. Path '$type', line 1, position 60.]
  at Program.Main(): line 18
```

https://dotnetfiddle.net/hNwczs

```csharp
using System;
using Newtonsoft.Json;

public class Program
{
	public static void Main()
	{
		var settings = new JsonSerializerSettings
		{
			TypeNameHandling = TypeNameHandling.Objects
		};
		
		var x = new ApiResponse<PageEditData>();
		var json = JsonConvert.SerializeObject(x, settings);
		
		Console.WriteLine(json);
		
		var result = JsonConvert.DeserializeObject<ApiResponse<PageEditData>>(
			json,
			settings
		);
        
        Console.WriteLine(result);
	}
}

public sealed class ApiResponse<T> { }
public sealed class PageEditData { }
```

**Comment by geoffreymcgill** [comment]
@DanTup Can you provide a simplified C# sample demonstrating how we can generate the same json serialized value? We'll use that sample to create some unit tests. 

```
"NewMind.Hercules.Common.APIs.ApiResponse`1[[CreateMailoutTask.KeyValuePairDataModel[], NewMind.Hercules.CreateMailoutTask]]"
```

**Comment by DanTup** [comment]
@geoffreymcgill Yep, I'll create a repro and send it over when back in the office on Monday.

**Comment by LeonidVeriga** [comment]
@DanTup, yes, there is one more case related to this issue. The reported use case was fixed and the fix included into **v.1.0**.  We have one more fix in PR #32. That would be great if you could check in (just rebuild the PR's branch in **Release** mode  - a Nuget package will be located in **..\Newtonsoft.Json\bin\Release** folder).

**Comment by geoffreymcgill** [comment]
Hi @DanTup, please let us know Monday morning if you're able to provide a reproducible sample.

We added a change (now in **master**) that should fix the issue, and we will release **v1.1** as soon as we can confirm the fix against your test case.

Thanks again for bringing this issue to our attention.

**Comment by DanTup** [comment]
I upgraded to Bridge 16.1 and Newtonsoft 1.1 in our app and still see the same error. I'm struggling to get a good repro in Deck though; so gonna try and do it a console app first (where I can roll Newtonsoft backwards/forwards) and post back in a bit.

**Comment by DanTup** [comment]
@geoffreymcgill Here's a repro of this. If you create a .NET and Bridge app with the assembly name set to "Demo" and the npaste this code in; it works with JSON.NET and fails with Bridge. The hard-coded JSON was created by JSON.NET (Bridge creates slightly different json - it lacks the assembly names).

```cs
using System;
using Newtonsoft.Json;

namespace Demo
{
	public class Program
	{
		public static void Main()
		{
			var json = @"{
   ""$type"":""Demo.ApiResponse`1[[Demo.KeyValuePairDataModel[], Demo]], Demo"",
   ""ResultIfSuccessful"":[
      {
         ""$type"":""Demo.KeyValuePairDataModel, Demo"",
         ""Key"":81,
         ""Value"":""BLA""
      }
   ]
}";

			var settings = new JsonSerializerSettings { TypeNameHandling = TypeNameHandling.Objects };
			var result = JsonConvert.DeserializeObject<ApiResponse<KeyValuePairDataModel[]>>(json, settings);
			Console.WriteLine(result.ResultIfSuccessful[0].Key);
		}
	}

	public sealed class KeyValuePairDataModel
	{
		public int Key;
		public string Value;
	}

	public sealed class ApiResponse<T>
	{
		public ApiResponse(T resultIfSuccessful)
		{
			ResultIfSuccessful = resultIfSuccessful;
		}

		public T ResultIfSuccessful { get; }

	}
}
```

The error is:

```text
newtonsoft.json.js:688 Uncaught TypeError: Cannot find type: Demo.ApiResponse`1[[Demo.KeyValuePairDataModel[], Demo]], Demo
    at Function.DeserializeObject (newtonsoft.json.js:688)
    at Function.Main (Demo.js:34)
    at bridge.js:2960
    at HTMLDocument.delayfn (bridge.js:480)
    at HTMLDocument.listenHandler (bridge.js:497)
```

I test using 16.1 and the 1.1 I just built from `master` from this repo.

Hope this helps!

**Comment by vladsch** [comment]
Related issue
https://github.com/bridgedotnet/Bridge/issues/3071

**Comment by LeonidVeriga** [comment]
@DanTup Additional test cases ([one](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/pull/36/commits/84d7f953b35ab816cdc9ff0bfbdad60444a0c4a0#diff-f2147c14bdb1493c3ee6fe22ef879feaR118) and [two](https://github.com/bridgedotnet/Bridge.Newtonsoft.Json/pull/36/commits/276b911edf6df3cb425bcc5792e4c86293c77bd8#diff-f2147c14bdb1493c3ee6fe22ef879feaR173)) fixed in **Newtonsoft.Json** **v.1.1.1** (depending on Bridge **v16.2**).
